### ISSUE TITLE
Excessive memory usage in L0Learn.cvfit with large n, small p

### ISSUE THREAD

**Issue by wbnicholson** [hazimehh/L0Learn#39] opened 2019-05-09 15:10 UTC
Hello,

Thanks for putting these methods together in an R package.  I'm interested in using it on a problem in which I have very large n (on the order of 2 million) and small p (on the order of 50).  

When I attempt to run `L0Learn.cvfit` memory usage explodes (several hundred gigabytes are used before R crashes).  What's more concerning is that the memory does not appear to be released when the function successfully finishes even after calling gc().  I'm assuming that there's some sort of memory leak in the C++ portion of your code.

I'm wondering if it's possibly related to your use of a .Call wrapper in line 39 of cvfit.R.  Since you export the C++ function `L0LearnCV` you should be able to directly access the function without the need for this wrapper.

I've included a reproducible example below.

```library(L0Learn)
n=2e6
set.seed(1) 
X = matrix(rnorm(n*10),nrow=n,ncol=100)
B = c(rep(1,5),rep(0,95))
e = rnorm(n)
y = X%*%B + e

mod <- L0Learn.cvfit(x=X,y=y,penalty="L0L2",intercept=FALSE,nLambda=50)

**Comment by hazimehh** [comment] 2019-05-25 03:31
Thank you so much for reporting the issue!  TL;DR: The issue is now fixed in v1.1.1, which can be installed from Github using:
```{R}
library(devtools)
install_github("hazimehh/L0Learn")
```
The update will be available on CRAN soon. 

Details: There were two separate problems: (1) the vector of residuals was being stored with every solution in the path (this is not actually needed and can lead to excessive mem consumption when n is large) and (2) in some cases, vectors were being dynamically allocated and never destroyed, which was leaking to the R session.

**Closed** 2019-05-25 03:32 UTC
